In [1]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv("data/EMSResponses.csv")
df.head()

,incident_ID,incident_date,priority,zone,time_phone_pickup,time_unit_arrived,time_incident_closed,disposition,council_district,census_state_code,census_county_code,census_tract,census_block,census_geoID,census_block_name
0,1,1/1/2012,4,City of Austin,12/31/2011 20:32:54,01/01/2012 03:03:07,01/01/2012 03:40:39,ATCEMS Transport,9,48,453,1100,1118,484530011001118,Block 1118
1,2,1/1/2012,4,City of Austin,01/01/2012 00:03:46,01/01/2012 00:35:56,01/01/2012 01:21:12,Patient Refusal,5,48,453,2428,1003,484530024281003,Block 1003
2,3,1/1/2012,4,City of Austin,01/01/2012 00:08:43,NaN,01/01/2012 00:11:29,No Patient / False Alarm,9,48,453,1100,1080,484530011001080,Block 1080
3,4,1/1/2012,2,City of Austin,01/01/2012 00:11:47,01/01/2012 00:17:22,01/01/2012 01:03:06,Patient Refusal,3,48,453,2314,2010,484530023142010,Block 2010
4,5,1/1/2012,3,City of Austin,01/01/2012 00:16:14,01/01/2012 00:24:58,01/01/2012 01:09:11,ATCEMS Transport,2,48,453,2430,1019,484530024301019,Block 1019

In [35]:
#Remove all of the temporal and non-unique data that we don't care about.
df.drop(["census_state_code", "census_county_code", "census_block_name", "zone"], axis = 1, inplace = True)

In [36]:
df.drop(["incident_date", "time_phone_pickup", "time_unit_arrived","time_incident_closed"], axis = 1, inplace = True)

In [39]:
df["disposition"][df["disposition"] == "<Missing>"] = "Other"

/home/lee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620352 entries, 0 to 620351
Data columns (total 7 columns):
incident_ID         620352 non-null int64
priority            620352 non-null int64
disposition         620352 non-null object
council_district    620352 non-null int64
census_tract        620352 non-null int64
census_block        620352 non-null int64
census_geoID        620352 non-null int64
dtypes: int64(6), object(1)
memory usage: 33.1+ MB

In [48]:
df.groupby("disposition").count()

,incident_ID,priority,council_district,census_tract,census_block,census_geoID
disposition,,,,,,
ATCEMS Transport,381823,381823,381823,381823,381823,381823
Cancelled,43441,43441,43441,43441,43441,43441
Deceased on Scene,4814,4814,4814,4814,4814,4814
No Patient / False Alarm,58220,58220,58220,58220,58220,58220
Other,1312,1312,1312,1312,1312,1312
Patient Refusal,95381,95381,95381,95381,95381,95381
Referred,35332,35332,35332,35332,35332,35332
Test,29,29,29,29,29,29